apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s

    scrape_configs:
      - job_name: 'django'
        static_configs:
          - targets: ['192.168.49.2:31800']
