apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31800
  selector:
    app: django
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - image: docker.io/martalp00/appp:proj
          name: app
          ports:
            - containerPort: 8000
              name: app
