apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31900
  selector:
    app: prometheus
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.33.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: configmap-prometheus
              mountPath: /etc/prometheus
      volumes:
        - name: configmap-prometheus
          configMap:
            name: configmap-prometheus
