kind: Secret
apiVersion: v1
metadata:
  name: docker-credentials
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYXJ0YWxwMDAiLCJwYXNzd29yZCI6Ik1hbG9wZS4xMyIsImVtYWlsIjoibWFydGFsbzEzMDRAZ21haWwuY29tIiwiYXV0aCI6ImJXRnlkR0ZzY0RBd09rMWhiRzl3WlM0eE13PT0ifX19
type: kubernetes.io/dockerconfigjson
